services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app        # monte ton code pour hot reload
      - /app/node_modules # préserver les modules installés dans l'image
    environment:
      - NODE_ENV=development
    command: npm run dev