services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: portfolio-app

    ports:
      - "${WEB_PORT}:3000"

    env_file:
      - .env

    restart: unless-stopped

    environment:
      - PORT=3000
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0